[0m11:39:37.711027 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028155012660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002815876C770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000281587EB2F0>]}


============================== 11:39:37.715027 | be0384ca-5f72-43fc-a169-12517773bd28 ==============================
[0m11:39:37.715027 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:39:37.716028 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Matt\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init ai_ingestion', 'send_anonymous_usage_stats': 'True'}
[0m11:39:37.737810 [debug] [MainThread]: Starter project path: C:\Users\Matt\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m11:39:37.753869 [info ] [MainThread]: 
Your new dbt project "ai_ingestion" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:39:37.754869 [info ] [MainThread]: Setting up your profile.
[0m11:39:37.755910 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m11:39:37.757909 [debug] [MainThread]: Command `dbt init` failed at 11:39:37.757909 after 0.15 seconds
[0m11:39:37.757909 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028158013D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000281585CAF30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028158A51A90>]}
[0m11:39:37.757909 [debug] [MainThread]: Flushing usage events
[0m11:40:23.071862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021663FBE630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021664A5B260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021663DB9880>]}


============================== 11:40:23.075957 | 772aa927-93ff-4254-88a5-af6b8cd166a3 ==============================
[0m11:40:23.075957 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:40:23.076955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Matt\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:40:23.076955 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Program Files (x86)\Engineering\src\data\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:40:23.077956 [debug] [MainThread]: Command `dbt run` failed at 11:40:23.077956 after 0.11 seconds
[0m11:40:23.078956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021664AE2780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021663FBE630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002166483A360>]}
[0m11:40:23.078956 [debug] [MainThread]: Flushing usage events
